# features: &features
#   stuff: true

default: &default
  # API_URL: "/api"
  # WEBFONTLOADER:
  #   classes: false
  #   events: false
  #   # typekit:
  #   #   id: "*******"
  # FEATURES:
  #   <<: *features

development:
  <<: *default

production: &production
  <<: *default

staging:
  <<: *production
